Areas/Admin/Controllers/TeacherController.cs

using BLL.BusinessManagers;
using BLL.BusinessManagers.AdminManager;
using BLL.BusinessManagers.SessionsManager;
using BLL.BusinessManagers.StudentManager;
using BLL.BusinessManagers.TeacherManager;
using BLL.BusinessManagers.UserManager;
using BLL.BusinessModels.AdminModels;
using BLL.BusinessModels.TeacherModels;
using BLL.Helpers;
using DAL.Entities;
using DAL.MasterEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static BLL.BusinessManagers.AdminManager.AdminManager;

namespace Tutoring.Areas.Admin.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager TeacherManager = new TeacherManager();
        UserActivities obj_Activity = null;
        UsersActivityManager ActivityMgr = new UsersActivityManager();
        MyDbContext context = new MyDbContext();

        // GET: Admin/Teacher
        public ActionResult Index()
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
              || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                return View();
            }

            else
                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });
        }

        public ActionResult ViewTeachers(int? flag)
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
                || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                var update = context.Notifications.Where(p => p.IsSeen != true).ToList();
                foreach (var item in update)
                {
                    long id = Convert.ToInt64(item.UserID);
                    var user = context.Users.Where(p => p.UserID == id).FirstOrDefault();
                    if (user.UserType == 3)
                    {
                        item.IsSeen = true;
                    }
                    
                }
                context.SaveChanges();
                ViewBag.TeachersMenu = "class = active";

            TeacherManager teacherMgr = new TeacherManager();
            AdminManager adminManager = new AdminManager();
            StudentManager studentMgr = new StudentManager();
            BLL.BusinessModels.TeacherModels.TeacherViewModel teacherModel = new BLL.BusinessModels.TeacherModels.TeacherViewModel();
          
            var teachersList = new List<BLL.BusinessModels.TeacherModels.TeacherViewModel>();

           
                if(flag == 2)
                {
                    ViewBag.totalTeachersRegistered = teacherMgr.GetTotalNoOfTeachersCount();
                    ViewBag.teachersRegisteredThisMonth = teacherMgr.GetTeachersRegisteredThisMonthCount();
                    ViewBag.teachersRegisteredToday = teacherMgr.GetTeachersRegisteredTodayCount();

                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                        ViewBag.currentUserPermissions = currentUserPermissions;

                    }

                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var userModel = teacherMgr.GetTeacherByUserID(item);
                        UserManager.ConvertUserViewModelToTeacherViewModel(userModel , ref teacherModel);
                        teachersList.Add(teacherModel);
                    }
                    return View(teachersList);
                }

                if(flag == 3)
                {
                    ViewBag.totalTeachersRegistered = teacherMgr.GetTotalNoOfTeachersCount();
                    ViewBag.teachersRegisteredThisMonth = teacherMgr.GetTeachersRegisteredThisMonthCount();
                    ViewBag.teachersRegisteredToday = teacherMgr.GetTeachersRegisteredTodayCount();
                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);
                        ViewBag.currentUserPermissions = currentUserPermissions;
                    }
                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var userModel = teacherMgr.GetTeacherByUserID(item);
                        UserManager.ConvertUserViewModelToTeacherViewModel(userModel, ref teacherModel);
                        teachersList.Add(teacherModel);
                    }
                    return View(teachersList);
                }

                if(flag == 4)
                {
                    ViewBag.totalTeachersRegistered = teacherMgr.GetTotalNoOfTeachersCount();
                    ViewBag.teachersRegisteredThisMonth = teacherMgr.GetTeachersRegisteredThisMonthCount();
                    ViewBag.teachersRegisteredToday = teacherMgr.GetTeachersRegisteredTodayCount();
                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);
                        ViewBag.currentUserPermissions = currentUserPermissions;
                    }
                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var userModel = teacherMgr.GetTeacherByUserID(item);
                        UserManager.ConvertUserViewModelToTeacherViewModel(userModel, ref teacherModel);
                        teachersList.Add(teacherModel);
                    }
                    return View(teachersList);
                }



                ViewBag.totalTeachersRegistered = teacherMgr.GetTotalNoOfTeachersCount();
                ViewBag.teachersRegisteredThisMonth = teacherMgr.GetTeachersRegisteredThisMonthCount();
                ViewBag.teachersRegisteredToday = teacherMgr.GetTeachersRegisteredTodayCount();

                var model = teacherMgr.ListofTeachers();

                if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                {
                    var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                    ViewBag.currentUserPermissions = currentUserPermissions;

                }

                return View(model);
            }
            else
            {
                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });
            }
        }

        public ActionResult BlockTeacher(Int64 userid)
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
               || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {

                var result = TeacherManager.BlockUser(userid);
                if (result == (int)Enumerations.ResponsHelpers.Block)
                {
                    ViewBag.Message = result;
                    
                }
                   
                return RedirectToAction("ViewTeachers");
            }

            else
                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });
        }

        public ActionResult ApproveTeacher(Int64 userid)
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
                || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                var result = TeacherManager.ActivateUser(userid);
                if (result == (int)Enumerations.ResponsHelpers.Block)
                    ViewBag.Message = result;

                obj_Activity = new UserActivities();
                obj_Activity.ActionPerformed = "Teacher got Appproved";
                obj_Activity.FKUserID = userid;
                obj_Activity.ActivitySource = (int)Enumerations.ActivitySource.BacksideActivity;
                ActivityMgr.AddActivity(obj_Activity);

                return RedirectToAction("ViewTeachers");
            }

            else
                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });

        }

        public ActionResult ViewDetails(int userid)
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
               || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                TeacherQualificationModel teacherModel = new TeacherQualificationModel();
                TeacherManager teacherManager = new TeacherManager();
                var usermodel = teacherManager.GetTeacherByUserID(userid);
                usermodel.teacherQualification = teacherManager.GetTeacherQualificationByUserID(userid);

                var teacherActivity = teacherManager.GetTeacherCompleteActivities(usermodel);

Areas/Support/Controllers/ChatController.cs
using BLL.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tutoring.Areas.Support.Controllers
{
   
    public class ChatController : Controller
    {
        // GET: Support/Chat
       
        public ActionResult Index()
        {
            if (Config.User ==null || Config.User.UserID <= 0)
            {
                return RedirectToAction("Login","Account",  new { area = "", @returnUrl = Url.Action("Index","Chat", new { area = "Support" }) });
            }
            return View();
        }

    }
}

Areas/Teacher/Views/Teacher/AddNotes.cshtml
@using BLL.BusinessModels.TeacherModels
@using BLL.Helpers
@model AddNotesViewModel
<style>
    .form-horizontal .form-group {
        margin-right: 0px !important;
        margin-left: 0px !important;
    }

    #FKTopicID:disabled {
        background: white;
    }
</style>


<div class="modal fade" id="Upload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content UploadVideo">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload New Note</h4>
            </div>
  
@using (Html.BeginForm("AddNotes", "Teacher", null, FormMethod.Post, new { @class = "form-horizontal", @id = "ReviewForm" , enctype = "multipart/form-data" }))
{
            @Html.HiddenFor(x=>x.FolderID)

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Title</label>
                                @Html.TextBoxFor(x => x.NotesTitle, new { @class = "form-control", @placeholder = "Title" })
                                @Html.ValidationMessageFor(x => x.NotesTitle, "", new { @class = "text-danger" })


                                @*<input type="text" class="form-control" placeholder="Title" />*@
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Subject</label>
                                @Html.DropDownListFor(x => x.FKSubjectID, Model.ListofTeacherSubjects, "Select Subject", new { @class = "form-control", @onchange = "LoadTopics()" })
                                @Html.ValidationMessageFor(x => x.FKSubjectID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">

                                <label>Select Topic</label>
                                @Html.DropDownListFor(model => model.FKTopicID, Enumerable.Empty<SelectListItem>(), "Select Topic", new { @class = "form-control", @disabled = "disabled" })
                                @Html.ValidationMessageFor(x => x.FKTopicID, "", new { @class = "text-danger" })

                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">

                                <label>Add New Topic (Optional)</label>
                                @Html.TextBoxFor(x => x.TopicOptional, new { @class = "form-control", @placeholder = "Topic Name" })

                            </div>
                        </div>

                        @*<div class="col-md-4">
                            <label>File Upload</label>
                            <label class="btn btn-primary btn-block btn-file">
                                Upload File <input type="file" style="display: none;">
                            </label>
                        </div>*@

                        <div class="form-group col-md-4">
                            <label> File Upload</label><br>
                            <label class="btn btn-success btn-block btn-file">
                                Upload File <input id="imgUpload" type="file" name="FileBase" data-val="true" data-val-required="File is required">
                            </label>
                            @Html.ValidationMessage("FileBase", "", new { @class = "text-danger" })
                            <div id="validatormsg" class="text-danger">

                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Description</label>
                                @Html.TextAreaFor(x => x.NotesDescription, new { @class = "form-control", @placeholder = "Description about resource", @rows = 7 })
                                @Html.ValidationMessageFor(x => x.NotesDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @*<a href="#" class="btn btn-success" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> Upload</a>
                <a href="#" class="btn btn-danger" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Cancel</a>*@
                
                @*<input type="submit" class="btn btn-success" value="Upload" />
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancel </button>*@

                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Upload</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"> <i class="glyphicon glyphicon-remove"></i> Cancel </button>

            </div>
}


        </div>
    </div>
</div>





<script type="text/javascript">

    function LoadTopics() {

        var GradeID = $("#FKSubjectID").val();
      
        if (GradeID != null && GradeID != '') {

            $.ajax({
                type: 'POST',
                url: '@Url.Action("TopicsListDrop", "Teacher")',
                dataType: 'json',
                data: { SubjectID: GradeID },
                success: function (cities) {
                    var gradesSelect = $('#FKTopicID');
                    gradesSelect.attr("disabled", false);

                    var txtstring = $('#FKTopicID option:first-child').text();
                    gradesSelect.empty();
                    gradesSelect.append('<option value="">' + txtstring + '</option>');
                    $.each(cities, function (i, val) {
                        gradesSelect.append('<option value="' + val.Value + '">' + val.Text + '</option>');
                    });
                },
                error: function (ex) {
                    ShowErrorNotification("Error", _AjaxErrorMessage);
                }
            });
        }

        else {
            $("#FKTopicID").attr('disabled', true);
        }
    }


    document.getElementById('imgUpload').onchange = function (chk) {
        $("#validatormsg").empty();
        var val = $(this).val();
        var input = this;
        switch (val.substring(val.lastIndexOf('.') + 1).toLowerCase()) {
            case 'pdf': case 'docx': case 'doc': case 'ppt': case 'pptx': case 'txt':
                var fileSize = input.files[0].size //size in kb
                fileSize = fileSize / 1048576;
                if (fileSize > 3) {
                    $(this).val('');
                    $("#validatormsg").empty();
                    $("#validatormsg").html("Please select less than 3MB file");
                }
                else {

                    $("#validatormsg").empty();
                    var names = input.files[0].name;
                    $("#validatormsg").html(names + " :  selected");

                }
                break;
            default:
                $(this).val('');
                $("#validatormsg").empty();
                $("#validatormsg").html("Only PDF,DOC,DOCX PPT,PPTX and Txt formats Allowed");
                break;

        }
    }


</script>

Areas/Teacher/Views/Teacher/AddResource.cshtml
@using BLL.BusinessModels.TeacherModels
@using BLL.Helpers
@model AddResourceViewModel
<style>

    .form-horizontal .form-group {
        margin-right: 0px !important;
        margin-left: 0px !important;
    }
     #FKTopicID:disabled {
        background: white;
    }
</style>

<div class="modal fade" id="WriteReviews" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content UploadVideo">
            
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload New Free Resources</h4>
            </div>


@using (Html.BeginForm("AddResource", "Teacher", null, FormMethod.Post, new { @class = "form-horizontal", @id = "ReviewForm" }))
{
    
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Title</label>
                                @Html.TextBoxFor(x=>x.ResourceTitle, new { @class = "form-control" ,@placeholder = "Title" })
                                @Html.ValidationMessageFor(x=>x.ResourceTitle,"", new { @class="text-danger"})
                          
                            </div>
                        </div>
                                
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Subject</label>
                                @Html.DropDownListFor(x=>x.FKSubjectID,Model.ListofTeacherSubjects,"Select Subject", new {@class="form-control", @onchange = "LoadTopics()" })
                                @Html.ValidationMessageFor(x=>x.FKSubjectID,"", new { @class="text-danger"})
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Year</label>
                                @Html.DropDownListFor(model => model.ResourceYear, Enumerable.Range(2000, (DateTime.Now.Year + 1) - 2000).Reverse().Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }), "Select Year", new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ResourceYear, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">

                                <label>Select Topic</label>
                                @Html.DropDownListFor(model => model.FKTopicID, Enumerable.Empty<SelectListItem>(), "Select Topic", new { @class = "form-control", @disabled = "disabled" })
                                @Html.ValidationMessageFor(x => x.FKTopicID, "", new { @class = "text-danger" })
                            
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">

                                <label>Add New Topic (Optional)</label> 
                                 @Html.TextBoxFor(x => x.TopicOptional, new { @class = "form-control", @placeholder = "Topic Name" })
                               
                           </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Video URL</label>

                                @Html.TextBoxFor(x => x.VideoURL, new { @class = "form-control", @placeholder = "Video URL" })
                                @Html.ValidationMessageFor(x => x.VideoURL, "", new { @class = "text-danger" })


                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Description</label>
                                @Html.TextAreaFor(x => x.ResourceDescription, new { @class = "form-control", @placeholder = "Description about resource" , @rows=7 })
                                @Html.ValidationMessageFor(x => x.ResourceDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="modal-footer">
                @*<a href="#" class="btn btn-success" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> Publish</a>
                <a href="#" class="btn btn-danger" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Cancel</a>*@
               
                <button type="submit" class="btn btn-success" ><i class="glyphicon glyphicon-ok"></i> Publish </button>
                
                 <button type="button" class="btn btn-danger" data-dismiss="modal"> <i class="glyphicon glyphicon-remove"></i> Cancel </button>
            
            </div>

}
       
         </div>
    </div>
</div>



<script type="text/javascript">

    function LoadTopics() {

        var GradeID = $("#FKSubjectID").val();
        alert("Load Topics : " + GradeID);
        if (GradeID != null && GradeID != '') {

            $.ajax({
                type: 'POST',
                url: '@Url.Action("TopicsListDrop", "Teacher")',
                dataType: 'json',
                data: { SubjectID: GradeID },
                success: function (cities) {
                    var gradesSelect = $('#FKTopicID');
                    gradesSelect.attr("disabled", false);

                    var txtstring = $('#FKTopicID option:first-child').text();
                    gradesSelect.empty();
                    gradesSelect.append('<option value="">' + txtstring + '</option>');
                    $.each(cities, function (i, val) {
                        gradesSelect.append('<option value="' + val.Value + '">' + val.Text + '</option>');
                    });
                },
                error: function (ex) {
                    ShowErrorNotification("Error", _AjaxErrorMessage);
                }
            });
        }

        else {
            $("#FKTopicID").attr('disabled', true);
        }
    }


</script>

Areas/Teacher/Views/Teacher/JoinSessions.cshtml
@model DAL.Entities.Sessions
@{
    ViewBag.Title = "JoinSessions";
    Layout = "~/Areas/Teacher/Views/Shared/_TeacherLayout.cshtml";
}

<div class="White79">
    <div class="GreyBg">
        <div class="container" style="width: 100%">
            <div class="col-md-12 TitleStripp">
                <div class="col-md-9">
                    <h2><i class="glyphicon glyphicon-list-alt"></i>My Session Requested</h2>
                </div>
                <div class="col-md-3">
                    @*<a href="MySessionBooked.html" class="btn mybtn btn-block">Session Scheduled</a>*@
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-md-12 nopadding">

                @if (Model != null)
                {
                    <h3 class="intt"> Join Sessions </h3>
                    <div class="col-md-12">
                        <table class="table table-bordered ssTable">
                            <thead>
                                <tr>
                                    <th>Session Details</th>
                                    <th>Action</th>
                                </tr>
                            </thead>


                            <tbody>
                                <tr>
                                    <td>

                                        <p class="sstime">Your session with @Model.RequestedByName on @Model.SubjectName is happening Now.</p>
                                    </td>

                                    <td>
                                     @*<a href="@Url.Action("index","whiteboard", new {area="", link=@Model.SessionLink,@SessionID=Model.TrialSessionID})" class="namme">Join Session</a><br>*@
                                        <a href="@Url.Action("conncet_bbb","Teacher","Teacher")" target="_blank" class="btn btn-dss">Join-Session</a> &nbsp;&nbsp;&nbsp;&nbsp;
                                        <a href="@Url.Action("cancel_bbb","Teacher","Teacher")" class="btn btn-dss">Cancel </a>
                                    </td>

                                </tr>

                            </tbody>

                        </table>
                    </div>
                }
                else
                {
                    <h2 class="title">NO SESSIONS FOUND</h2>
                }

            </div>
        </div>
    </div>
</div>

Areas/Teacher/Views/Teacher/SessionsScheduled.cshtml
@model List<DAL.Entities.Sessions>
@{
    ViewBag.Title = "SessionsScheduled";
    Layout = "~/Areas/Teacher/Views/Shared/_TeacherLayout.cshtml";
}

<div class="White79">
    <div class="GreyBg">
        <div class="container" style="width: 100%">
            <div class="col-md-12 TitleStripp">
                <div class="col-md-9">
                    <h2><i class="glyphicon glyphicon-list-alt"></i>My Session Scheduled</h2>
                </div>
                <div class="col-md-3">
                    <a href="@Url.Action("MySessions","Teacher", new { area="Teacher"})" class="btn mybtn btn-block">Session Requested</a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-md-10 col-md-offset-1 TPBbox">
                <h3 class="intt">UPCOMING SESSION</h3>
                @if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <div class="col-md-12 ssbox flex">
                            <div class="col-xs-1 nopadding">
                                @if (string.IsNullOrEmpty(item.ImageName))
                    { <img src="~/Content/Front/frontimg/noimage.jpg" id="imgChange" class="ssuser" />}
                    else
                    { <img src="~/UserImages/@item.ImageName" id="imgChange" class="ssuser" />}

                            </div>
                            <div class="col-xs-9">
                                <h2>Session on  @item.SubjectName - <span> @item.TopicName </span></h2>
                                <p>Student : <a href="#">@item.RequestedByName</a></p>
                                <h5>
                                    Session on : <span>
                                        @item.SessionTimes
                                    </span>
                                </h5>
                            </div>
                            <div class="col-xs-2 showda nopadding">
                                <h1>@item.TrialHappenDate.Day</h1>
                                <h2>@item.TrialHappenDate.ToString("MMM")</h2>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <h2 class="title">NO UPCOMING SESSIONS</h2>
                }
         
            </div>
        </div>
    </div>
</div>
