Areas/Admin/Controllers/StudentController.cs
using BLL.BusinessManagers;
using BLL.BusinessManagers.AdminManager;
using BLL.BusinessManagers.SessionsManager;
using BLL.BusinessManagers.StateManager;
using BLL.BusinessManagers.StudentManager;
using BLL.BusinessManagers.TeacherManager;
using BLL.BusinessManagers.UserManager;
using BLL.BusinessModels.AdminModels;
using BLL.BusinessModels.StudentModels;
using BLL.Helpers;
using DAL.Entities;
using DAL.MasterEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Tutoring.Areas.Admin.Controllers
{
    public class StudentController : Controller
    {
        UsersActivityManager activityMgr = new UsersActivityManager();
        UserActivities obj_activity = null;
        MyDbContext context = new MyDbContext();
        // GET: Admin/Student
        public ActionResult Index(int? flag)
        {
            ViewBag.StudentsMenu = "class = active";
            StudentManager studentMgr = new StudentManager();
            AdminManager adminManager = new AdminManager();

            var usersList = new List<UserViewModel>();
            var update = context.Notifications.Where(p => p.IsSeen != true).ToList();
            foreach (var item in update)
            {
                long id = Convert.ToInt64(item.UserID);
                var user = context.Users.Where(p => p.UserID == id).FirstOrDefault();
                if (user.UserType == 4 || user.UserType == 5)
                {
                    item.IsSeen = true;
                }

            }
            context.SaveChanges();
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
                || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                if (flag == 1)
                {
                    ViewBag.TotalStudentsCount = studentMgr.TotalStudentsCount();
                    ViewBag.TotalStudentsRegisteredThisMonthCount = studentMgr.TotalStudentsRegisteredThisMonthCount();
                    ViewBag.TotalStudentsRegisteredTodayCount = studentMgr.TotalStudentsRegisteredTodayCount();

                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                        ViewBag.currentUserPermissions = currentUserPermissions;

                    }

                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var model = studentMgr.GetStudentByID(item);
                        usersList.Add(model);
                    }
                    return View(usersList);
                }

                if (flag == 2)
                {
                    ViewBag.TotalStudentsCount = studentMgr.TotalStudentsCount();
                    ViewBag.TotalStudentsRegisteredThisMonthCount = studentMgr.TotalStudentsRegisteredThisMonthCount();
                    ViewBag.TotalStudentsRegisteredTodayCount = studentMgr.TotalStudentsRegisteredTodayCount();

                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                        ViewBag.currentUserPermissions = currentUserPermissions;

                    }

                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var model = studentMgr.GetStudentByID(item);
                        usersList.Add(model);
                    }
                    return View(usersList);
                }

                if (flag == 3)
                {
                    ViewBag.TotalStudentsCount = studentMgr.TotalStudentsCount();
                    ViewBag.TotalStudentsRegisteredThisMonthCount = studentMgr.TotalStudentsRegisteredThisMonthCount();
                    ViewBag.TotalStudentsRegisteredTodayCount = studentMgr.TotalStudentsRegisteredTodayCount();

                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                        ViewBag.currentUserPermissions = currentUserPermissions;

                    }

                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var model = studentMgr.GetStudentByID(item);
                        usersList.Add(model);
                    }
                    return View(usersList);
                }
                if (flag == 4)
                {
                    ViewBag.TotalStudentsCount = studentMgr.TotalStudentsCount();
                    ViewBag.TotalStudentsRegisteredThisMonthCount = studentMgr.TotalStudentsRegisteredThisMonthCount();
                    ViewBag.TotalStudentsRegisteredTodayCount = studentMgr.TotalStudentsRegisteredTodayCount();

                    if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                    {
                        var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                        ViewBag.currentUserPermissions = currentUserPermissions;

                    }

                    var studentsIds = TempData["studentIds"] as List<long>;
                    foreach (var item in studentsIds)
                    {
                        var model = studentMgr.GetStudentByID(item);
                        usersList.Add(model);
                    }
                    return View(usersList);
                }

                var studentsList = studentMgr.GetStudentsList();

                ViewBag.TotalStudentsCount = studentMgr.TotalStudentsCount();
                ViewBag.TotalStudentsRegisteredThisMonthCount = studentMgr.TotalStudentsRegisteredThisMonthCount();
                ViewBag.TotalStudentsRegisteredTodayCount = studentMgr.TotalStudentsRegisteredTodayCount();

                if (Config.User.UserType == (int)Enumerations.UserType.Admin)
                {
                    var currentUserPermissions = adminManager.GetPermissionIDsOfUserbyUserID(Config.CurrentUser);

                    ViewBag.currentUserPermissions = currentUserPermissions;

                }
                return View(studentsList);
            }
            else

                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });
        }


        public ActionResult CreateStudent()
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
                || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                var studentModel = new UserViewModel();
                studentModel.IsActive = true;
                studentModel.UserType = (int)Enumerations.UserType.Student;
                studentModel.UserStatus = (int)Enumerations.UserStatus.IsActive;

                CurriculumsManagers curriculumsMgr = new CurriculumsManagers();

                var curriculumsList = curriculumsMgr.GetCurriculumsList();
                studentModel.CurriculumsList = studentModel.GetCurriculumsList(curriculumsList);

                StudentManager curriculumMgr = new StudentManager();
                var gradesList = curriculumMgr.GetGradesListByCurriculumID(1);
                studentModel.GradesList = studentModel.GetGradesList(gradesList);

                StateManager stateManager = new StateManager();
                var statesList = stateManager.GetAllStates();
                studentModel.StatesList = studentModel.GetStatesList(statesList);

                return View(studentModel);
            }
            else
                return RedirectToAction("UnAuthorizeAccess", "Home", new { area = "" });


        }

        [HttpPost]
        public ActionResult CreateStudent(UserViewModel userModel)
        {
            if (Config.CurrentUser == 0)
                return RedirectToAction("Login", "Account", new { area = "" });

            if (Config.User.UserType == (int)Enumerations.UserType.Super
                || Config.User.UserType == (int)Enumerations.UserType.Admin)
            {
                if (ModelState.IsValid)
                {
                    StudentManager obj_stdManager = new StudentManager();
                    userModel.LoginEmail = userModel.LoginEmail.ToLower();
                    userModel.IsActive = true;
                    userModel.IsVerified = (int)Enumerations.VerificationType.VerifiedByAdmin;
                    userModel.UserStatus = (int)Enumerations.UserStatus.Approved;
                    userModel.curriculumViewModel.IsActive = true;
                    userModel.gradeViewModel.IsActive = true;
                    userModel.UsersProfileViewModel.FKOccupationId = (int)Enumerations.Occupation.Student;

                    var newStudent = obj_stdManager.CreateNewStudent(userModel);
                    if (newStudent.Response == (int)Enumerations.ResponsHelpers.Created)
                    {
                        obj_activity = new UserActivities();

Areas/Student/Controllers/SubscribeController.cs
using BLL.BusinessManagers.AdminManager;
using BLL.BusinessModels;
using BLL.Helpers;
using DAL.Entities;
using DAL.MasterEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tutoring.Areas.Student.Controllers
{
    public class SubscribeController : Controller
    {
        string msg = "";
        MyDbContext context = new MyDbContext();

        CurriculumsManagers cManager = new CurriculumsManagers();
        // GET: Student/Subscribe
        public ActionResult Index()
        {
            
            return View(ListSubRequests());
        }
        public List<Subjects> ListBySubjects(Int64 CurriculumID)
        {
            try
            {

                List<Subjects> list = new List<Subjects>();
                list = context.Subjects.Where(x => x.FKCurriculumID == CurriculumID && x.IsActive == true).ToList();
                if (list != null && list.Count > 0)
                {
                    list.ForEach(x => {
                        x.GradeName = context.Grades.Where(y => y.GradeID == x.FKGradeID).Select(y => y.GradeName).FirstOrDefault().ToString() + " - " + context.Subjects.Where(y => y.SubjectID == x.SubjectID).Select(y => y.SubjectName).FirstOrDefault();
                    });

                    return list;
                }
                else
                {
                    return null;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }
        public List<Subjects> ListByAllSubjects()
        {
            try
            {

                List<Subjects> list = new List<Subjects>();
                list = context.Subjects.Where(x => x.IsActive == true).ToList();
                if (list != null && list.Count > 0)
                {
                    list.ForEach(x => {
                        x.GradeName = context.Grades.Where(y => y.GradeID == x.FKGradeID).Select(y => y.GradeName).FirstOrDefault().ToString() + " - " + context.Subjects.Where(y => y.SubjectID == x.SubjectID).Select(y => y.SubjectName).FirstOrDefault();
                    });

                    return list;
                }
                else
                {
                    return null;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }
        public ActionResult Create()
        {


            StudentReqSubModel model = new StudentReqSubModel();
            model.ListofCurriculums = cManager.dListOfCurriculums();
            model.ListofSubjects = cManager.dListOfSubjects();
            ViewBag.ConfirmationMessage = TempData["ConfirmationMessage"];

            return View(model);
        }
        public ActionResult AddStudentReqSub(StudentReqSubModel model)
        {
            try
            {
                var obj = new DAL.Entities.StudentReqSub
                {
                    CreatedBy = Config.CurrentUser,
                    IsActive = true
                };
                obj.LookingFor = model.LookingFor;
                obj.StartDate = model.StartDate;
                obj.CurriculumId = model.CurriculumId;
                obj.SubjectId = model.SubjectId;
                obj.Remarks = model.Remarks;

                context.StudentReqSubs.Add(obj);
                context.SaveChanges();
                Int64 id = obj.Id;
                msg = "Your request submitted successfully.";


                StudentReqSubModel model2 = new StudentReqSubModel();
                model.ListofCurriculums = cManager.dListOfCurriculums();
                model.ListofSubjects = cManager.dListOfSubjects();
                TempData["ConfirmationMessage"]  = msg;

                return RedirectToAction("Create");
               
            }
            catch (Exception ex)
            {
                @ViewBag.ConfirmationMessage = "Unable to submit request. Please contact to administrator!!!";

                throw ex;
            }
        }
        public List<StudentReqSub> ListSubRequests()
        {
            try
            {

                List<StudentReqSub> list = new List<StudentReqSub>();
                list = context.StudentReqSubs.ToList();
                if (list != null && list.Count > 0)
                {
                    list.ForEach(x =>
                    {

                        x.Curriculum = context.Curriculums.Where(y => y.CurriculumID == x.CurriculumId).Select(y => new { Name = y.CurriculumName }).FirstOrDefault().Name.ToString();
                        x.Subject = context.Subjects.Where(y => y.SubjectID == x.SubjectId).Select(y => new { Name = y.SubjectName }).FirstOrDefault().Name.ToString();
                        

                    });

                    return list;
                }
                else
                {
                    return null;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }
        public List<CoursesHeader> ListByCurriculumsAll()
        {
            try
            {

                List<CoursesHeader> list = new List<CoursesHeader>();
                list = context.CourseHeader.Where(x => x.IsActive == true).ToList();
                if (list != null && list.Count > 0)
                {
                    list.ForEach(x => {

                        x.CourseParticipants = context.CourseParticipants.Where(y => y.FKCourseID == x.CoursesHeaderID).ToList();
                        x.TeacherName = context.UsersProfile.Where(y => y.FKUserID == x.FKOfferedBY).Select(y => new { Name = y.FirstName + " " + y.LastName }).FirstOrDefault().Name.ToString();
                        x.GradeName = context.Grades.Where(y => y.GradeID == x.FKGradeID).Select(y => y.GradeName).FirstOrDefault().ToString() + " - " + context.Subjects.Where(y => y.SubjectID == x.FKSubjectID).Select(y => y.SubjectName).FirstOrDefault();
                        x.TeacherPic = Convert.ToString(context.UsersProfile.Where(y => y.FKUserID == x.FKOfferedBY).Select(y => y.ProfilePic).FirstOrDefault());

                    });

                    return list;
                }
                else
                {
                    return null;
                }

            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

Areas/Support/Controllers/ChatController.cs
using BLL.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tutoring.Areas.Support.Controllers
{
   
    public class ChatController : Controller
    {
        // GET: Support/Chat
       
        public ActionResult Index()
        {
            if (Config.User ==null || Config.User.UserID <= 0)
            {
                return RedirectToAction("Login","Account",  new { area = "", @returnUrl = Url.Action("Index","Chat", new { area = "Support" }) });
            }
            return View();
        }

    }
}

Areas/Student/Views/Student/Index.cshtml
@using BLL.Helpers
@model BLL.BusinessModels.StudentModels.StudentDashboardViewModel

@{ 
    int status = ViewBag.Status;
}

<style>
    .ECmain .listing {
        padding: 15px 0px !important;
    }

        .ECmain .listing .box {
            height: 250px;
            background: #f2f2f2;
            box-shadow: none;
        }

            .ECmain .listing .box .bottom {
                background: #b5b5b5;
            }

    .progress {
        margin-bottom: 5px;
    }

    .ECmain .listing .box .teacher {
        padding: 7px 0px;
        margin-bottom: 10px;
        border-top: 1px solid #cacaca;
        margin-top: 10px;
    }
</style>

<div class="White79">
    <div class="TeacheProfileTop dash-title">
        <div class="container">
            <div class="col-md-12">
                <div class="col-sm-6">
                    <h2><span>Welcome</span> @Model.FirstName @Model.LastName</h2>
                </div>
                <div class="col-sm-6 text-right">
                    <h2>₹ <span>0.00</span></h2>
                    <a href="#">
                        <p>Wallet Balance</p>
                        <h2><i class="glyphicon glyphicon-menu-right"></i></h2>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="GreyBg">
        <div class="container">
            <div class="col-md-12 dash-top">
                <div class="col-md-4">
                    <div class="col-md-12 dash-box">
                        <h3>Help</h3>
                        <p>Feel free to contact us anytime, we are here to help! Our experience team member will back to you withing 24 working hrs.</p>
                        <a href="@Url.Action("support","student", new { area="student"})">Support</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-12 dash-box">
                        <h3>System Check Tool</h3>
                        <p>Check your system readiness for Live session. Ensure trouble-free sessions by checking your system's Audio / Video and other settings. </p>
                        <a href="@Url.Action("systemCheck","student", new { area="student"})">Run System Check</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-12 dash-box" style="background: #dcdcdc">
                        <h3>Create a subscription</h3>
                        <p>Get in touch if you want a new subscription as per your learning requirement OR want to extend your subscription with existing teacher.</p>
                        <a href="@Url.Action("Create","Subscribe", new { area="student"})">Subscribe teacher</a>
                    </div>
                </div>
            </div>



            <div class="col-md-12 dash-top">
                <div class="col-md-4">
                    <div class="col-md-12 dash-box">
                        <h3>Monthly Tution</h3>
                        <p>Feel free to contact us anytime, we are here to help! Our experience team member will back to you withing 24 working hrs.</p>
                        <a href="@Url.Action("Monthlytution","Home", new { area=""})">Support</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-12 dash-box">
                        <h3>System Check Tool</h3>
                        <p>Check your system readiness for Live session. Ensure trouble-free sessions by checking your system's Audio / Video and other settings. </p>
                        <a href="@Url.Action("systemCheck","student", new { area="student"})">Run System Check</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-12 dash-box" style="background: #dcdcdc">
                        <h3>Create a subscription</h3>
                        <p>Get in touch if you want a new subscription as per your learning requirement OR want to extend your subscription with existing teacher.</p>
                        <a href="@Url.Action("Create","Subscribe", new { area="student"})">Subscribe teacher</a>
                    </div>
                </div>
            </div>

            <div class="col-md-12 mtb40">
                <div class="col-md-7 dash-session-no">
                    <h3 class="dash-title2">Your Upcoming Sessions</h3>


                    @if (Model.listOfUpcomingSession != null && Model.listOfUpcomingSession.Count > 0)
                    {
                        foreach (var item in Model.listOfUpcomingSession)
                        {
                            <div class="col-md-12 dash-uss">
                                <div class="col-xs-1 nopadding">
                                    @if (string.IsNullOrEmpty(item.ImageName))
                                    {<img src="~/Content/Front/frontimg/noimage.jpg" class="ssuser" />}
                                    else
                                    { <img src="~/UserImages/@item.ImageName" class="ssuser" />}


                                </div>
                                <div class="col-xs-10">
                                    <h2>Session on  @item.SubjectName - <span><b> @item.TopicName </b></span></h2>
                                    <p>Teacher : <a href="@Url.Action("TeacherProfile","Student", new {area="Student", TeacherID=@item.FKRequestedTo})"><b>@item.RequestedToName</b></a></p>
                                    <h5>
                                        Session on :
                                        <span>
                                            <b>
                                                @item.SessionTimes
                                            </b>
                                        </span>
                                    </h5>
                                </div>

                            </div>
                        }
                        <a href="@Url.Action("UpcomingSessions","Student", new { area="Student"})" class="btn btn-xs btn-default pull-right">View Detail</a>

                    }
                    else
                    {
                        <h4>NO UPCOMING SESSIONS</h4>
                    }
                </div>
                <div class="col-md-5 dash-session-no" style="border-right: none">
                    <h3 class="dash-title2">Notifications</h3>
                    @if (Model.listOfMyNotifications != null && Model.listOfMyNotifications.Count > 0)
                    {
                        foreach (var item in Model.listOfMyNotifications)
                        {

                            <div class="col-md-12 notilst">
                                <h6>@item.ActionPerformed</h6>
                                <p>@item.Time.ToString("dd MMM, yyyy | hh:mm tt")</p>
                            </div>

                        }

                        <div class="col-md-12 centeralign">
                            <br>
                            <a href="@Url.Action("allNotification","student", new { area="student"})" class="btn btn-xs btn-primary">View all Notification</a>
                        </div>
                    }
                    else
                    {
                        <div class="col-md-11 col-md-offset-1">
                            <img src="~/Content/Include/img/dashboard/icon2.png" />
                            <h4>No Notification Exist</h4>

                        </div>
                    }

                    <div class="col-md-12">

                        <br />&nbsp;
                    </div>
                    <h3 class="dash-title2">Activities</h3>

                    @if (Model.listOfUserActivities != null && Model.listOfUserActivities.Count > 0)
                    {
                        CustomTimeZone czone = new CustomTimeZone();
                        foreach (var item in Model.listOfUserActivities)
                        {


                            <div class="col-md-12 notilst">
                                <h5>@item.Comments</h5>
                                <p>

                                    @item.ActivityDateTime.ToString("dd MMMM yyyy | hh:mm tt")

                                </p>
                            </div>

                        }

                        <div class="col-md-12 centeralign">
                            <br>
                            <a href="@Url.Action("allActivities", "student", new { area = "student" })" class="btn btn-xs btn-primary">View all Activities</a>

                        </div>
                    }
                    else
                    {
                        <div class="col-md-11 col-md-offset-1">
                            <img src="~/Content/Include/img/dashboard/icon2.png" />
                            <h4>No Activity Exist</h4>

                        </div>
                    }


                </div>
            </div>

        </div>
    </div>
    <div class="dash-subscription ECmain">
        <div class="container">
            <div class="col-md-12">
                <div class="col-md-12">
                    <h3 class="dash-title2">Your Active Subscription</h3>
                </div>
                @if (ViewBag.Subscription != null && ViewBag.Subscription.Count > 0)
                {
                    <div class="col-md-12 listing">
                        @foreach (var item in ViewBag.Subscription)
                        {
                            <div class="col-md-3 col-sm-6">
                                <a href="@Url.Action("SubscriptionDetail","Student",new {@CourseID=@item.FKCourseID })">
                                    <div class="col-md-12 box">
                                        <h1>@item.Course.CourseTitle</h1>
                                        <h2>Start Date : @Convert.ToDateTime(item.Course.StartDate).ToString("dd-MMMM-yyyy")</h2>
                                        <div class="col-md-12 teacher">
                                            <p>Teacher</p>

                                            @if (string.IsNullOrEmpty(item.Course.TeacherPic))
                                            { <img src="~/Content/Front/frontimg/noimage.jpg" />}
                                            else
                                            { <img src="~/UserImages/@item.Course.TeacherPic" />}

                                            <span style="color: #444; font-family: Dbold">@item.Course.TeacherName</span>
                                        </div>
                                        <div class="col-md-12 bottom">
                                            @*<div class="progress">
                                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;">0%</div>
                                                </div>*@
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width:2em; width: @item.CompletionPercentage%;">
                                                    @if (item.CompletionPercentage > 0)
                                                    {
                                                        @item.CompletionPercentage@Html.Raw("%")
                                                    }
                                                    else
                                                    {
                                                        @Html.Raw("0%")
                                                    }

                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </a>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <hr />
                        <h3>
                            No Subscription Found
                        </h3>
                }
               
            </div>
        </div>
    </div>
</div>

